---
# see: https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml
wordpressPassword: password

service:
  type: NodePort

persistence:
  storageClass: standard
  size: 500Mi
volumePermissions:
  enabled: true

mariadb:
  primary:
    persistence:
      storageClass: standard
      size: 500Mi
