---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: wordpress-manifests
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: mysql
data:
  password: cGFzc3dvcmQ=
