---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  namespace: wordpress-manifests
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: wordpress
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
