---
# see: https://gitea.com/gitea/helm-chart
gitea:
  admin:
    username: admin
    password: password
    email: admin@example.com

service:
  http:
    type: NodePort

persistence:
  enabled: true
  storageClass: standard
  size: 500Mi

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: standard
      size: 500Mi
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
