---
# see: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort

  ingress:
    enabled: false
