---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: gitea-manifests
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: postgres
data:
  password: cGFzc3dvcmQ=
